


spring:
 datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm
    username: root
    password: 1234
 
 jpa:
   hibernate.ddl-auto: update
   generate-ddl: true
   show-sql: false
   
server:
  port: 8083  
